var I18N = {};

I18N.conf = {

    /**
     * 可以解析的组件伪类名
     */
    // reComponentClasses: [

    // 页面级组件: 均位于 #vss_1 .internal-content-host 下
    // https://{account}.visualstudio.com/{project}/**
    // "project-overview-page-container", // Overview -> Summary
    // "dashboard-landing", // Overview -> Dashboards
    // "wiki-container", // Overview -> Wiki
    // "work-items-hub-view", // Work -> Work Items
    // "work-items-hub-row", // Work -> Work Items/Row
    // "board-content-view",          // Work -> Boards / https://{account}.visualstudio.com/{project}/{team}/_boards
    // "backlog-content-view", // Work -> Backlogs
    // "sprint-view-container", // Note: 和 .internal-content-host 同级,应该是一个BUG
    // "queries-view", // NOTE: 监听不到这个节点被新增,此组件的翻译只能递归节点时来检查节点是否为组件
    // "versioncontrol-explorer-view", // Note: 不在 .internal-content-host 下
    // "versioncontrol-git-history-view", // Code -> Commites
    //"versioncontrol-pushes-view", // Code -> Pushers
    // "vc-newbranches-view", // Code -> Branches
    // "git-tags-page", // Code -> Tags
    // "versioncontrol-pullrequest-list-view", // Code -> PRs
    // "versioncontrol-pullrequest-create-view", // Code -> PRs -> Create
    // "build-title-bar", // build
    // "pivotTab-link",

    // "work-item-form-main",  // 工单的编辑页面 / https://{account}.visualstudio.com/{project}/_workitems/edit/{id}

    // // Widgets
    // "assigned-to-me", // 我的任务
    // "buildchart-container", // 构建图表
    // "new-work-item",

    // // Dialogs
    // "new-workitem-dialog", // 创建工单
    // "vc-create-tag-dialog", // 创建代码 Tag  NOTE: 此节点不直接添加,此组件的翻译只能递归节点时来检查节点是否为组件

    // // 区域刷新
    // "zerodata", // 列表没有数据时
    // "grid-header-column", // 动态加载的表头列
    // "edit-readme-cta", // Overview -> Summary
    // "wiki-edit", // Overview -> Wiki
    // "wiki-new-page", // Overview -> Wiki
    // "commandbar-item", // 菜单项, 有大量菜单项被动态添加,尝试一下统一翻译
    // "vss-PickList--row", //"vss-PickList--element",  // 表格的下拉筛选器,应该时这个吧,先试试
    // "vss-PickList--noItemsText", // 下拉框没有数据时的提示
    // "ms-ContextualMenu-item", // 左侧菜单鼠标悬浮滑出子菜单
    // "ms-Tooltip", // 浮动提示
    // "ms-Button-textContainer", // 补充按钮文本
    // "ms-CommandBarItem-link", // 链接按钮
    // "ms-Dropdown-item", // 还是操作按钮
    // "ms-DetailsHeader-cell", // 表格的表头
    // "members-title-div", // 项目首页成员标题
    // "activity-panel", // 项目首页活动面板
    // ],

    /**
     * 需要跳过的节点
     */
    reIgnoreClasses: [
        "work-item-title", // 工单列表中的标题列
        "work-item-state-cell", // 工单列表中的状态列
		"workitem-state-value", // 待办页面工单状态列
        "markdown-render-area",  // markdown 文本渲染区域
    ],
};

I18N.zh = {
    "__common": {
        "static": {
            "@Me": "@我",

            "1 Day": "1 天",
            "7 Days": "7 天",
            "30 Days": "30 天",
            "7-day pass rate": "最近7天成功率",

            "Acceptance Criteria": "验收标准",
            "Accepted By": "由他确认",
            "Accepted Date": "确认日期",
            "Actions": "操作",
            "Activated By": "由他激活",
            "Activated Date": "激活日期",
            //"Active": "已确认(Active)",
            "Activity": "动态", // TODO: 在工作项中有字段名称也是'Activity'，但显然不是这个意思
            "Activity Date": "最后更新时间",
            "Add a column": "增加一列",
            "Add attachment": "增加附件",
            "Add Feature": "增加特性",
            "Add tag": "添加标签",
            "Add link": "添加关联",
            "Add or remove columns. To change the column order, drag and drop a field, or use the keyboard shortcuts, Ctrl+Up or Ctrl+Down.": "添加或删除列。如需更改列的显示顺序，请拖放字段或使用键盘快捷键，Ctrl + ↑ 或Ctrl + ↓ 。",
            "Add to favorites": "收藏",
            "Add up to 10 fields in the order that you want them to appear on the card.": "按照您希望它们显示在卡片上的顺序最多添加10个字段。",
            "Additional fields": "附加字段",
            "Admin settings": "设置",
            "All clear!": "全清!",
            "All your work items are displayed in a single lane. To view additional lanes, add new swimlanes.": "您的所有工作项都显示在一个泳道中，要查看其他泳道，请先添加新的泳道。",
            "An estimate of the number of units of work remaining to complete this bug": "估计解决此BUG还需要多少单位的工作量",
            "An estimate of the number of units of work remaining to complete this task": "估计完成此任务还需要多少单位的工作量",
            "Annotation": "提示",
            "Annotations": "提示",
            "Are you sure you want to delete the selected work item(s)?": "你确定要删除这些选中的工单吗?",
            "Are you sure you want to leave the page?": "你确定要离开页面吗？",
            "Area": "功能区域",
            "Area filter": "功能区域过滤",
            "Area Path": "功能分区",
            "Assessment of the effect of the bug on the project": "评估BUG对项目所产生的影响",
            "Assigned To": "指派给",
            "Assigned to": "指派给",
            "Assigned to me": "指派给我",
            "Assigned to filter": "指派过滤",
            "Attachments": "附件",

            "Back to Work Items": "返回到工单",
            "Back to \"Assigned to me\" tab (Alt + Q)": "返回\"指派给我\"页面(Alt + Q)",
            "Back to \"Recently created\" tab (Alt + Q)": "返回\"最近创建\"页面(Alt + Q)",
            "Backlog": "待办",
            "Backlog navigation levels": "导航上呈现的待办事项",
            "Backlogs": "待办",
            "Board": "看板",
            "Boards": "看板",
            "Bold (Ctrl+B)": "粗体 (Ctrl+B)",
            "Branches": "分支",
            "Bugs appear as children of requirements and are prioritized with tasks. They are moved across columns on the task boards.": "将 BUG 视为需求的子项，优先于任务。它们可以任务板上的列之间穿梭移动。",
            "Bugs are not prioritized against other work on the backlogs, and do not appear on either backlogs or boards. Your main method for managing bugs is through a work item query.": "BUG 不会出现在待办清单和看板中，也不会得到任何优先于其他工单的处理。管理 BUG 的主要方式是通过工单筛选器手动查询。",
            "Bugs appear on the Kanban board and product backlog where they can be prioritized with requirements. They also appear with requirements on the task boards, where they can be broken down into tasks.": "BUG 将出现在看板和产品待办清单上，可以根据需求对其进行优先级排序。同时它们也和需求一样出现在任务板上，而且也可以将他们分解成任务。",
            "Bugs are managed with requirements.": "BUG 和需求统一管理。",
            "Bugs are managed with tasks.": "BUG 和任务统一管理",
            "Bugs are not managed on backlogs and boards.": "在待办清单和看板中都不对 BUG 进行管理",
            "Build": "构建",
            "Build & Release": "构建和发布",
            "Build and release": "构建和发布",
            "Build Definitions": "Build 定义",
            "Build ID or build number": "Build Id 或内部版本号",
            "Builds": "构建",
            "Builds succeeded": "成功的构建",
            "Bulleted list": "无序列表",
            "Business = Customer-facing epics; Architectural = Technology initiatives to support current and future business needs": "Business = 给客户带来商业价值的史诗任务; Architectural = 支持当前及未来业务需求所需要开展的技术措施",
            "Business = delivers value to a user or another system; Architectural = work to support other stories or components": "Business = 为用户或其他系统提供商业价值; Architectural = 支持其他用户故事的组件或工作",
            "Business = Services provided by the system to fulfill stakeholder needs; Architectural = Technical system services to implement business features that deliver solution value": "Business = 系统提供的服务，用以满足利益相关者的需求; Architectural = 技术系统服务，用以实现提供解决方案价值的业务功能",
            "Business importance. 1=must fix; 4=unimportant.": "业务重要性。1=必须修复; 4=不重要。", //TODO: 此条翻译失败，原因待查
            "Business Value": "商业价值",

            "Cancel": "取消",
            "Capacity and burndown are based on the days your team works.": "将基于此设置来计算团队工作容量和燃尽图",
            "Card reordering": "卡片排序方式",
            "Cards": "卡片",
            "Change": "切换页面",
            "Changed Date": "最后修改时间",
            "Change type...": "改变类型...",
            //"Chart is unavailable to screenreaders. Sibling table element contains screen reader available representation of chart": "",
            //"Chart screen reader information.": "",
            "Chart": "图表",
            "Charts": "图表",
            "Check if you want to display fields, even when they are empty.": "即使字段是空字段的也进行显示",
            "Choose the expected reorder behavior for your work items.": "选择工单的预期排序方式。",
            "Classification": "分类",
            "Clear": "清除",
            "Click": "点击",
            "Close": "关闭",
            "Close (ESC)": "关闭 (ESC)",
            "closed": "关闭的",
            //"Closed": "关闭的(Closed)",
            "Change to Closed when the issue is resolved or not relevant anymore": "在问题解决或不再具有相关性时，将状态更改为已结束(Closed)",
            "Code": "代码",
            // "Code": "代码动态",s
            "Color": "颜色",
            "Column": "列",
            "Column name": "列名称",
            "Column Options": "列设置",
            "Column options": "列设置",
            "Columns": "列",
            "Columns visualize the flow of work across the board.": "使用列来全面可视化定义工作流程",
            "completed": "已完成的",
            "Commits": "查看提交",
            "Commit": "提交",
            "Completed": "完成",
            "Completed Work Items": "已完结的工单",
            "Comment": "注释",
            "Commits": "提交",
            "Configure team settings": "团队设置",
            "Confirm": "确认",
            "Copy to clipboard": "复制到剪贴板",
            "Core fields": "核心字段",
            "Create copy of work item...": "创建工单副本",
            "Create link": "创建链接",
            "Create new project": "创建一个新项目",
            "Create project": "新建项目",
            'Create query': '新建筛选器',
            "created": "新建的",
            "Created Date": "创建日期",
            "Cumulative flow": "累积流",
            "Cumulative flow diagram": "累积流图(CFD)",
            "Current": "当前",
            "Customize": "个性化",

            "Dashboards": "仪表板",
            "Date": "日期",
            "Decrease indent": "减少缩进",
            "Default branch summary": "默认分支摘要",
            "Default lane": "默认泳道",
            "Delete": "删除",
            "Delete work item(s)": "删除工作项",
            "Design": "设计",
            "Details": "详情",
            "Development": "开发",
            "Definitions": "定义",
            "Deployment": "部署实施",
            "Deployments succeeded": "成功的部署",
            "Deployment groups": "部署分组",
            "Description": "描述",
            "Description or acceptance criteria for this epic to be considered complete": "完整的的史诗故事必须包含能够清晰描述该史诗故事的描述或标准",
            "Description or acceptance criteria for this feature to be considered complete": "完整的的特性必须包含能够清晰描述该特性的描述或标准",
            "Description or reference to the story that must work for this work to be considered complete": "完整的的用户故事必须包含能够清晰描述该用户故事的描述或引用",
            "Development hasn't started on this item.": "与此工单相关的开发工作暂未开始",
            "Discard": "放弃",
            "Discussion": "话题讨论",
            "Documentation": "文档撰写",
            "Don't miss important work": "不要错过重要的工作",
            "Download as Zip": "下载为 Zip",
            "Due Date": "截止日期",

            "e.g., Tags:\"Release Blocker\"": "例如: Tags:\"Release Blocker\"",
            "(e.g., ToDo OR revisit)": "(例如: ToDo OR revisit)",
            "Edit in Wiki": "在 Wiki 中编辑此页", // 翻译失败, 会再次动态生成节点 .edit-readme-cta
            "Edit in Wiki": "在 Wiki 中编辑此页",
            "Edit page": "编辑页面",
            "Effort": "工作量",
            "Effort (Hours)": "工作量(小时)",
            'Email': '通过邮件发送',
            "Email...": "通过邮件发送...",
            "Email work item": "发送到邮件",
            "Emphasize selected tags using colors. Only one color applies to a tag at a time.": "使用颜色强调标签，一个标签只能选择一个颜色。",
            "Enabled": "启用",
            "Enter full screen mode": "进入全屏模式",
            "Enter full screen mode (Z)": "进入全屏模式(Z)",
            "Enter title": "输入标题",
            "Epic": "史诗故事",
            "Epics": "史诗故事",
            "Epics backlog": "史诗故事待办清单",
            "Epics Backlog": "史诗故事待办清单",
            "Epics Board": "史诗故事看板",
            "Epics": "史诗故事",
            "Existing item": "现有的项",
            "Exit full screen mode": "退出全屏模式",
            "Exit full screen mode (z)": "退出全屏模式",

            "Favorites": "收藏",
            "Feature": "特性",
            "Features": "特性",
            "Features backlog": "特性待办清单",
            "Features Board": "特性看板",
            "Field": "字段",
            "Field 'Title' cannot be empty.": "'标题'字段不能为空",
            "Fields": "字段",
            "File": "文件",
            "Files": "代码浏览",
            "Filter": "过滤",
            "Filter by field": "根据字段过滤",
            "Filter by keyword": "关键词过滤",
            "Filter projects": "项目过滤",
            "Folder": "文件夹",
            "Folder / Name": "文件夹/名称",
            "Follow": "跟进",
            "Following": "我跟进的",
            "Found in Build": "发现于构建",
            "Friday": "星期五",

            "General": "常规",
            "Get help": "获取帮助",
            'Get started with your product backlog': '从产品待办清单开始',

            "Help": "帮助",
            "Hide": "隐藏",
            "Hide filters": "隐藏过滤器",
            "History": "历史",
            "How does the business value decay over time. Higher values make the epic more time critical": "商业价值会随着时间的流逝而衰退，商业价值更高的史诗故事往往需要更紧迫的时间",
            "How does the business value decay over time. Higher values make the feature more time critical": "商业价值会随着时间的流逝而衰退，商业价值更高的特性往往需要更紧迫的时间",
            "How to see the bug. End by contrasting expected with actual behavior.": "清晰的描述BUG如何重现的步骤。并且在最后，说明预期行为与实际行的对比。",

            "Implementation": "实现",
            "Import": "导入",
            "Importance to business": "对业务的重要性",
            //"In Progress": "处理中(In Progress)",
            "In Progress Items": "处理中(In Progress)的工单",
            "Include the first column of the Kanban board": "包含看板中的第一列",
            "Include the last column of the Kanban board": "包含看板中的最后一列",
            "Increase indent": "增加缩进",
            "Initial value for Remaining Work - set once, when work begins": "当开始此项工作时，一次性设置一个预估需要的时间",
            "Insert image": "插入图片",
            "Integrated in Build": "集成于构建",
            "Integrated in build": "集成于构建",
            //"Interactive chart. Chart. Use up and down arrows to navigate with most screen readers.": "",
            "Issue": "问题",
            "Italic (Ctrl+I)": "斜体 (Ctrl+I)",

            "Keep an eye on important work": "请时刻关注重要的工作",
            "Keyboard shortcuts": "键盘快捷键",

            "Last built": "最近一次运行",
            "Learn more about @mentions": "了解有关 @提到 的更多信息",
            'Learn more about backlogs': '了解有关待办清单的更多信息',
            "Learn more about following": "详细了解以下内容",
            "Learn more about the bug management setting.": "了解有关BUG管理的相关设置(英文)",
            "Leave": "离开",
            "Leave blank to display the last 30 weeks of activity.": "留空则显示最近30周的活动。",
            "Learn more": "了解详情",
            "Library": "库",
            "Link type": "链接类型",
            "Links": "链接",
            "Live updates": "实时更新",
            //"Load test" : "测试",
            "Loading...": "加载中...",
            "Loading identities....": "身份加载中...",

            //"Machines" : "测试",
            "Manage folders": "管理文件夹",
            "Manage Team Members": "管理团队成员",
            "Maximize Development": "最大化开发面板",
            "Maximize Discussion": "最大化话题讨论面板",
            "Maximize Description": "最大化描述面板",
            "Maximize Related Work": "最大化相关工作面板",
            "Maximize Repro Steps": "最大化重现步骤面板",
            "Maximize System Info": "最大化系统信息面板",
            "Members and Activity": "成员 & 动态",
            "Members": "成员",
            "Mentioned": "@提到过我",
            "Mine": "我的",
            "Monday": "星期一",
            "More Actions...": "更多...",
            "More save options": "更多保存选项",
            "Move to team project": "移动到团队项目",
            "My activity": "我的活动",
            "My accounts": "我的账户",
            "My organizations": "我的组织",
            "My profile": "个人档案",

            "Name": "名称",
            "New": "新建", // TODO: 新建按钮 
            //"New": "待确认(New)",
            "New = for triage; Active = not yet fixed; Resolved = fixed not yet verified; Closed = fix verified.": "New = 等待; Active = 尚未修复; Resolved = 已修复但未验证; Closed = 修复得到验证",
            "New = New work not yet activated; Active = work remains to be done; Closed = tested and checked in.": "New = 未激活的新任务; Active = 任务进行中未完成; Closed = 经过测试并签入",
            "New = Not started yet; Active = work remains to be done; Resolved = awaiting acceptance tests; Closed = acceptance tests passed": "New = 尚未开始; Active = 工作待完成; Resolved = 等待验收测试; Closed = 验收测试通过",
            "New branch...": "新建分支...",
            "New item": "创建新项",
            "New linked work item": "新建关联工单",
            "New page": "新建页面",
            "New query": "新建筛选器",
            "New Sprint": "新建冲刺计划",
            "New work item": "新建工单",
            "New Work Item": "新建工单",
            "Next work item in the \"Assigned to me\" tab (Alt + N)": "\"指派给我\"页面的下一个工单 (Alt + N)",
            "Next work item in the \"Recently created\" tab (Alt + N)": "\"最近创建\"页面的下一个工单 (Alt + N)",
            "No attachments have been added": "没有任何附件",
            "No areas available": "当前没有任何功能区域",
            "No links have been added": "暂未添加任何链接",
            "No pull requests need your attention": "没有拉取请求需要您留意",
            "No tags available": "当前没有任何标签",
            "No types available": "当前没有任何工单类型",
            "No states available": "当前没有任何工单状态",
            'No work items match your filter': '哦哟，你的筛选条件什么也查不到咧(^-^偶尔也皮一下)',
            'No work scheduled yet': '还没有工作安排',
	    "Note":"说明",
            "Notification settings": "通知设置",
            //"Number of Commits per day": "",
            "Numbered list": "有序列表",

            "Off": "关闭",
            "On": "开启",
            "OK": "确定",
            "Open in Queries": "筛选器中打开",
            'Open filtered view in Queries': '在筛选器中打开筛选的结果',
            "Open selected items in Queries": "在查询中打开所选项目",
            "Operators": "操作符",
            "Original Estimate": "初步估计",
            "Overview": "总览",

            "Packages": "程序包",
            "Pin item": "固定到快捷栏",
            "Planning": "计划",
            "Priority": "优先级",
            "Project documentation": "项目说明文档",
            "Project Information": "项目信息",
            "Project name": "项目名称",
            "Project settings": "项目设置",
            "Projects": "项目",
            "Projects contain your source code, work items, automated builds and more.": "一个包含您的源代码,工作项,自动构建等相关信息的项目。",
            "Previous work item in the \"Assigned to me\" tab (Alt + P)": "\"指派给我\"页面的上一个工单 (Alt + P)",
            "Previous work item in the \"Recently created\" tab (Alt + P)": "\"最近创建\"页面的上一个工单 (Alt + P)",
            "Preview features": "预览新功能",
            "Priority for completing the epic, based on business goals": "基于业务目标评定史诗任务的优先级",
            "Priority for completing the feature, based on business goals": "基于业务目标评定特性的优先级",
            "Problem, resolution plan and status": "问题，解决方案和状态",
            "Pull Requests": "拉取请求",
            "Pull requests": "拉取请求",
            "Pushes": "推送记录",

            "Queries": "筛选器",
            "Queued": "队列中",
            "Quickly take action on items where you have been @mentioned.": "您可以快速对@您的工单开展工作。",

            "Readme": "自述",
            "Reason": "原因",
            "Recycle Bin": "回收站",
            "Recently updated": "最近更新",
            "Recently completed": "最近完成",
            "Recently created": "最近创建",
            "Refresh": "刷新",
            "Related pages": "相关页面",
            "Related Work": "相关工作",
            "Releases": "发布",
            "Remaining": "余量",
            "Remove Formatting": "清楚格式",
            "Remove from favorites": "取消收藏",
            "Remove link": "取消关联",
            "Remove this column": "移除此列",
            "Rename": "重命名",
            "Repositories": "代码库",
            "Repository": "代码库",
            "Repro Steps": "重现步骤",
            "Requested by me": "由我请求",
            "Requirements": "需求调研",
            "Resolved Reason": "解决方案",
            "Restore": "恢复",
            "Restore Development": "还原开发面板",
            "Restore Description": "还原描述面板",
            "Restore Discussion": "还原话题讨论面板",
            "Restore Related Work": "还原相关工作面板",
            "Restore Repro Steps": "还原重现步骤面板",
            "Restore System Info": "还原系统信息面板",
            "Revert changes": "还原更改",
            "Right Pane": "右侧面板",
            "Risk": "风险",
            "Running": "运行中",
            //"Runs" : "测试",

            "Saturday": "星期六",
            "Save": "保存",
            "Save & Close": "保存并关闭",
            "Search": "搜索",
            //"Search": "键入关键词开始搜索", //todo:
            "Security": "安全",
            "See only the backlogs your team manages.": "只能看到您的团队参与的待办事项。",
            "Select days": "选择工作日",
	    "Selected Work Items":"已选择的工单",
	    "Send":"发送",
	    "Send work items in email": "通过邮件发送工单",
            "Set your team's preference for how they manage bugs. Your selection determines where bugs appear in the hierarchy and on backlogs and boards.": "设置您的团队对如何管理错误的偏好。您的选择决定了层次结构中以及积压和板上出现错误的位置。",
            "Settings": "设置",
            "Severity": "严重性",
            "Show": "显示",
            "Show Assigned To as:": "显示分配给：",
            "Show empty fields": "显示空字段",
            "Show filters": "显示过滤器",
            "Show ID": "显示 ID",
            "Show less information": "折叠",
            "Show Tags": "显示标签",
            "Show the important information to your team. Fields are editable directly on the card.": "在卡片上向您的团队显示重要的信息，这些字段也可以直接在卡片上编辑。",
            "Show visual cues on cards.": "在卡片上显示视觉提示",
            "Sign out": "退出",
            "Sorting": "排序",
            "Sprints": "冲刺",
            "Stack Rank": "堆栈等级",
            "Start date": "开始日期",
            // "Start storyboarding"
            "State": "状态",
            "State Graph": "状态变更图",
            "State mapping": "映射到状态",
            "Status": "状态",
            "States": "工单状态",
            "States filter": "状态过滤",
            "Stay": "留下",
            "Stories": "用户故事",
            "Stories backlog": "用户故事待办清单",
            "Stories Board": "用户故事看板",
            "Stories": "用户故事",
            "Story Points": "故事点",
	    "Subject":"主题",
            "succeeded": "成功",
            "Sunday": "星期日",
            "Suggestions": "建议",
            "Summary": "概要",
            "Swimlane": "泳道",
            "Swimlanes": "泳道",
            "Swimlanes visualize different classes of work as horizontal lanes on the board.": "泳道可视为不同类型的工单在看板上的水平车道。",
            "System Info": "系统信息",

            "Tag": "标签",
            "Tag colors": "标签颜色",
            "Tags": "标签",
            "Tags": "标签",
            "Tags": "标签",
            "Tags": "标签",
            "Tags filter": "标签过滤",
            "Target Date": "目标日期",
            "Templates": "模板",
            "Task": "任务",
            "Task groups": "任务分组",
            "Test": "测试",
            "Test Case": "测试用例",
            //"Test Plans*" : "测试计划*",
            "Test Plan": "测试计划",
            "Test Suite": "测试套件(Test Suite)",
            "Testing": "测试",
            "There are no links in this group.": "此组中没有链接。",
            "The area of the product to which this task contributes": "此任务贡献的产品区域",
            "The area of the product with which this bug is associated": "与此BUG相关联的产品功能区域",
            "The area of the product with which this epic is associated": "与此史诗故事相关联的产品功能区域",
            "The area of the product with which this feature is associated": "与此特性相关联的产品功能区域",
            "The area of the product with which this issue is associated": "与此问题相关联的产品功能区域",
            "The area of the product with which this user story is associated": "与此用户故事相关联的产品功能区域",
            "The build in which the bug was found": "BUG产生于哪一次构建",
            "The build in which the bug was fixed": "BUG修复于哪一次构建",
            "The business value for the customer when the epic is released": "史诗故事发布给客户带来的商业价值",
            "The business value for the customer when the feature is released": "特性发布给客户带来的商业价值",
            "The date by which this issue needs to be closed": "计划关闭此问题的日期",
            "The estimated effort to implement the feature": "预估实现特性所需要的工作量",
            "The estimated effort to implemented the epic": "预估实现史诗所需要的工作量",
            "The first column is mapped to the initial state used when a work item is created.": "第一列映射到创建工作项时使用的初始状态。",
            "The iteration within which this bug will be fixed": "该BUG计划在哪个迭代进行修复",
            "The iteration within which this epic will be implemented": "该史诗故事计划在哪个迭代中实现",
            "The iteration within which this feature will be implemented": "该特性计划在哪个迭代中实现",
            "The iteration within which this issue will be fixed": "该问题计划在哪个迭代中解决",
            "The iteration within which this task will be completed": "该任务计划在哪个迭代中完成",
            "The iteration within which this user story will be implemented": "该用户故事计划在哪个迭代中实现",
            "The number of units of work that have been spent on this bug": "已经消耗在这个BUG上的工作量",
            "The number of units of work that have been spent on this task": "已经消耗在这个任务上的工作量",
            "The reason why the bug is in the current state": "BUG之所以处于当前状态的原因",
            "The reason why the epic is in its current state": "史诗故事之所以处于当前状态的原因",
            "The reason why the feature is in its current state": "特性之所以处于当前状态的原因",
            "The reason why the issue is in the current state": "问题之所以处于当前状态的原因",
            "The reason why the story is in its current state": "用户故事之所以处于当前状态的原因",
            "The reason why the task is in its current state": "任务之所以处于当前状态的原因",
            "The reason why the bug was resolved": "错误解决的原因",
            "The size of work estimated for fixing the bug": "估计修复这个BUG的工作量",
            "The size of work estimated for implementing this user story": "估计实现这个用户格式的工作量",
            "The target date for completing the epic": "完成史诗任务的目标日期",
            "The target date for completing the feature": "完成特性的目标日期",
            "This account": "本账户内搜索",
            "This project": "本项目内搜索",
            "Thursday": "星期四",
            "Time Criticality": "时间紧迫性",
            //"Time range for showing activity data": "",
            "Title": "标题",
	    "To":"收件人",
            "to get updates about the items you want to track.": "获取跟进的工单的进度更新。",
            "Triggered by": "触发",
            "Tuesday": "星期二",
            "Type of work involved": "该工单的工作形式",
            "Types filter": "类型过滤",
            "Types": "工单类型",

            "Unassigned": "未指派",
            "Uncertainty in feature": "特性面临不确定性时，用于提示风险",
            "Uncertainty in requirement or design": "需求和设计面临不确定性时，用于提示风险",
            "Underline (Ctrl+U)": "下划线 (Ctrl+U)",
            "Unpin item": "从快捷栏取消固定",
            "Unsaved Changes": "未保存的数据更改",
            "Upload file(s)": "上传文件",
            "Usage": "使用详情",
            'Use the "New Work Item" command to create and prioritize work items': '使用“新建工单”命令创建工单并设置其优先级',
            "User Story": "用户故事",

            "Value area": "价值范围",
            "Velocity": "速率",
            "Version control": "版本控制系统",
            "View options": "设置",
            "Visualization": "可视化",
            "Visualize your lead time, work in progress, and any bottlenecks in your process.": "可视化您的交付周期、正在进行的工作并直观的提示工作流程中的任何瓶颈。",

            "Wednesday": "星期三",
            "What's new in VSTS": "VSTS 新特性(英文)",
            "Work": "工作",
            "Working days": "工作日",
            "Working with bugs": "BUG处理",
            "Work first on items with lower-valued stack rank. Set in triage.": "优先处理较低堆栈等级的项目",
            "What to do, pointers to resources and inputs, design notes, exit criteria": "该怎么做，指明资源和输入条件、设计说明、以及完成标准",
            "Work Items": "工单",
            "Work item process": "工作组织流程",
            "Work items follow the backlog order when changing columns.": "更改列时，工单按照待办清单中的顺序排序。",
            "Work items reorder when changing columns, and the backlog reflects the new order.": "更改工单所处的列时将重新排序，并将最新的排序同步到待办清单中。",

            // X

            "You can restore deleted work items from the Recycle Bin until they are permanently deleted based on auto-delete settings (disabled).": "在它们根据自动删除设置（已禁用）被永久删除之前，您都可以从回收站还原已删除的工作项。",
            "You have modified this work item.  Close and lose changes?": "您已经修改了工单，关闭此页面会导致修改丢失，确认吗？",
            "You have unsaved changes made to the settings which will be lost. Are you sure you want to discard these changes?": "您有未保存的设置更改即将丢失，您确认要放弃这些更改关闭窗口吗?",
        },
        "regexp": [
            [/by (\d+) authors/, "由 $1 个作者提交"],
            [/(\d+) comments/, "$1 条讨论话题"],
            [/Planned Effort: (\d+|-)/, "计划工作量: $1"],
            [/(\d+) working days/, "$1 个工作日"],
            [/(\d+) of (\d+) Features completed/, "$2 个特性中已完成 $1 个"],
	    [/(\d+)\/(\d+) characters/, "$1/$2 个字符"],
        ]
    },

    "richeditor-toolbar": {
        "static": {
            "Remove link": "移除链接",
        }
    }
};
